apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: ta-mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sql-travelagency-sc